Add in User Agent Randomizer / Anonymization
samc621/SneakerBot pull request #39
Opened 2021-07-06 13:19 UTC by labboy0276

Adds User Agent Randomizer / Anonymization, helps with headless users.

2021-07-09 15:23 UTC, samc621 commented
Hi @labboy0276 I am testing this now. It appears to help with some issues on the footsites, but not doing anything for the CORS issue on Nike. It triggers this modal.

![Screen Shot 2021-07-09 at 11 22 35 AM](https://user-images.githubusercontent.com/38767335/125101214-fa64c380-e0a7-11eb-92dd-cbdb50f2e127.png)

 I think you mentioned hitting that issue, correct? Was this fix helping you bypass it?

2021-07-09 19:26 UTC, labboy0276 commented
@samc621 Yeah I don't think it will do anything for a CORS issue.  It just mocks the user agent for us.  

If you want to put the output of the CORS error into #28 I will see if I can figure it out this weekend or next.

2021-07-09 21:13 UTC, samc621 commented
@labboy0276 yup I gotcha, randomizing the UA is a good idea anyways. Merging this now!

As for the Nike error, I saw this modal when I ran the bot in headful mode. I didn't realize it was a CORS issue until I checked the requests in the network tab. I don't think there was anything in the response body, just a CORS error. You should be able to repro it pretty easily.

2021-07-09 21:14 UTC, samc621 requested changes
@labboy0276 thanks for this, and congrats on your first PR! Just one inline issue.

2021-07-09 21:14 UTC, samc621 commented on helpers/cluster.js
> +
Actually @labboy0276 it looks like this extra line break is causing an error with the linter. Mind removing it? Then this LGTM!

2021-07-17 18:17 UTC, samc621 commented
@labboy0276 just pinging you again in case you missed my [comment](https://github.com/samc621/SneakerBot/pull/39#discussion_r667214467) above.

2021-07-17 18:33 UTC, labboy0276 commented
@samc621 all set

2021-07-17 18:43 UTC, samc621 approved these changes
@labboy0276 thank you for this, and congrats on your first PR! Your work on the antibot stuff will be very helpful and appreciated!

2021-07-17 18:43 UTC, merged